### PR TITLE
Custom lotus parser json exception

### LINKED ISSUE #46: Customize JSON parsing errors
I've been using Lotus::Router (with Lotus::Controller) in building an API, and I find the ability to specify JSON parsing via `Lotus::Router.new parsers: [:json]` very convenient. However, the router responds with a very verbose message and stacktrace when a parsing error is encountered:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 2372
Content-Type: text/plain

JSON::ParserError: 757: unexpected token at '{
  "fruit": "Apple"
  "vegetable": "Cabbage"
}
'
	/Users/Erol/.gem/ruby/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	/Users/Erol/.gem/ruby/2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/routing/parsing/json_parser.rb:12:in `parse'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/routing/parsers.rb:52:in `block in _redefine_call'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/routing/http_router.rb:112:in `raw_call'
	/Users/Erol/.gem/ruby/2.2.0/gems/http_router-0.11.1/lib/http_router.rb:142:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/lotus-router-0.2.1/lib/lotus/router.rb:879:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/rack_patch.rb:13:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
	/Users/Erol/.gem/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

Is there a way to silence or customize the error response when running on production? I'm willing to submit a PR if there is no facility yet to do this and if you feel this is a worthy feature. :)

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
Closes #46 

Raise a custom lotus exception when the json parser fails to parse a malformed json.

If you have to implement a middleware to rescue json parser errors raised from lotus json parser, you can rescue `Lotus::Routing::Parsing::JsonParsingException` exception instead `JSON::ParseError` exception.

cc @lotus/core-team

### CODE REVIEW

**Comment by joneslee85** [comment]
:+1:

File: lib/lotus/routing/parsing/json_parser.rb [hunk 1]
```diff
@@ -3,6 +3,13 @@
 module Lotus
   module Routing
     module Parsing
+      # Json parsing error
+      # This is raised when the json parser fails to parse a json string.
+      #
+      # @since x.x.x
+      class JsonParsingException < ::StandardError
```
Comment (jodosha) [inline lib/lotus/routing/parsing/json_parser.rb]: This should be `BodyParsingError`.

Third party parsers may want to raise the same exception. For instance:

```ruby
class XmlParser
  # ...

  def parse(body)
    # parse xml
    rescue SomeXmlParsingException => e
      raise Lotus::Routing::Parsing::BodyParsingError.new(e)
  end
end
```

We can have only one exception for all the MIME type/parsers. From a final developer perspective, it's easier to catch only one exception:

```ruby
begin
  router.call(env)
rescue Lotus::Routing::Parsing::BodyParsingError => e
  # handle exceptions for JSON/XML/whatever ..
end
```

File: lib/lotus/routing/parsing/json_parser.rb [hunk 2]
```diff
@@ -10,6 +17,8 @@ def mime_types
 
         def parse(body)
```
Comment (jodosha) [inline lib/lotus/routing/parsing/json_parser.rb]: We should add API doc to document this new error here and for `Parser`.
Please remember to update README section as well. Thank you!

File: lib/lotus/routing/parsing/json_parser.rb [hunk 3]
```diff
@@ -3,13 +3,32 @@
...
         end
 
+
+        # Parse a json string
+        #
+        # @param body [String] a json string
+        #
+        # @return [Hash] the parsed json
+        #
+        # @raise [BodyParsingError] when the body can't be parsed.
```
Comment (jodosha) [inline lib/lotus/routing/parsing/json_parser.rb]: `Lotus::Routing::Parsing::BodyParsingError` :wink:

File: lib/lotus/routing/parsing/json_parser.rb [hunk 4]
```diff
@@ -3,13 +3,32 @@
 module Lotus
   module Routing
     module Parsing
+      # Json parsing error
+      # This is raised when the json parser fails to parse a json string.
+      #
+      # @since x.x.x
+      class BodyParsingError < ::StandardError
```
Comment (jodosha) [inline lib/lotus/routing/parsing/json_parser.rb]: This must be defined in `lib/lotus/routing/parsing/parser.rb`, as we need to make it available for custom parsers.

File: README.md [hunk 5]
```diff
@@ -615,7 +621,9 @@ class XmlParser
 
   # Parse body and return a Hash
   def parse(body)
-    # ...
+    # parse xml
+  rescue Lotus::Routing::Parsing::BodyParsingError => e
```
Comment (jodosha) [inline README.md]: it's

```ruby
def parse(body)
  # parse xml
rescue SomeXmlParsingError => e
  raise Lotus::Routing::Parsing::BodyParsingError.new(e)
end
```

**Comment by jodosha** [comment]
@AlfonsoUceda This looks good, thank you! :+1:

**Comment by thhermansen** [comment]
:+1: Thanks!

**Comment by jodosha** [comment]
@thhermansen Thank you for this good catch! :+1:
